title: Celeste
description: "A minimalist theme focused on simplicity"
encoding: utf-8

sidebar_close_on_outside_click: true

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock", "tmp.txt"]